<a href="https://colab.research.google.com/github/MuskanBansal2001/MB_Python_Tut_practice/blob/main/Python2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

In [7]:
x = np.array([i for i in range(10)])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.where(x%2==0,'even','odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd'], dtype='<U4')

In [11]:
condList = [x<5, x>6]
choiceList = [x**2, x**3]

In [12]:
np.select(condList, choiceList, default=x)

array([  0,   1,   4,   9,  16,   5,   6, 343, 512, 729])

In [15]:
arr = np.array([[3,4,5],[6,3,2],[63,4,5]])
arr

array([[ 3,  4,  5],
       [ 6,  3,  2],
       [63,  4,  5]])

In [16]:
np.amin(arr)

2

In [17]:
np.amin(arr,axis=0)

array([3, 3, 2])

In [18]:
np.amin(arr,axis=1)

array([3, 2, 4])

In [19]:
np.max(arr)

63

In [20]:
np.min(arr)

2

In [22]:
np.amax(arr,axis=0)

array([63,  4,  5])

In [23]:
np.amax(arr,axis=1)

array([ 5,  6, 63])

In [24]:
np.median(arr)

4.0

In [25]:
np.mean(arr)

10.555555555555555

In [26]:
np.std(arr)

18.57783094091277

In [27]:
np.var(arr)

345.1358024691358

In [28]:
np.percentile(arr,50)

4.0

In [30]:
bo = np.array([32,4,5,3,6,565,3])
bo

array([ 32,   4,   5,   3,   6, 565,   3])

In [31]:
np.sin(bo*np.pi/100)

array([ 0.84432793,  0.12533323,  0.15643447,  0.09410831,  0.18738131,
       -0.89100652,  0.09410831])

In [33]:
np.cos(bo*np.pi/100)

array([0.53582679, 0.9921147 , 0.98768834, 0.99556196, 0.98228725,
       0.4539905 , 0.99556196])

In [34]:
np.tan(bo*np.pi/100)

array([ 1.57574786,  0.12632938,  0.15838444,  0.09452783,  0.1907602 ,
       -1.96261051,  0.09452783])

In [35]:
bo = np.array([32,4,5,3,6,565,3])
bo

array([ 32,   4,   5,   3,   6, 565,   3])

In [36]:
np.floor(bo)

array([ 32.,   4.,   5.,   3.,   6., 565.,   3.])

In [37]:
np.ceil(bo)

array([ 32.,   4.,   5.,   3.,   6., 565.,   3.])

In [54]:
oneD = np.array([3,453,5,65,2,2,2])
twoD = np.array([[23,45,34,2,3],[45,32,32,3,43]])
threeD = np.array([[[4,2,43,54],[23,5,432,2]],[[43,23,4,4,54],[34,5,45,43]],[[23,45,34,2,3],[45,32,32,3,43]]])

<ipython-input-54-a7205b6b1e3b>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  threeD = np.array([[[4,2,43,54],[23,5,432,2]],[[43,23,4,4,54],[34,5,45,43]],[[23,45,34,2,3],[45,32,32,3,43]]])


In [39]:
oneD

array([  3, 453,   5,  65,   2,   2,   2])

In [40]:
twoD

array([[23, 45, 34,  2,  3],
       [45, 32, 32,  3, 43]])

In [56]:
threeD

array([[list([4, 2, 43, 54]), list([23, 5, 432, 2])],
       [list([43, 23, 4, 4, 54]), list([34, 5, 45, 43])],
       [list([23, 45, 34, 2, 3]), list([45, 32, 32, 3, 43])]],
      dtype=object)

In [42]:
oneD[0]

3

In [43]:
oneD[1]

453

In [44]:
oneD[2]

5

In [45]:
oneD[-3]

2

In [46]:
twoD[0,0]

23

In [47]:
twoD[0,1]

45

In [48]:
twoD[1,0]

45

In [50]:
twoD[1,2]

32

In [51]:
twoD[1,-1]

43

In [58]:
threeD[0,0,0]

IndexError: ignored