<a href="https://colab.research.google.com/github/MuskanBansal2001/MB_Python_Tut_practice/blob/main/Python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arra = np.array([1,2,3,4])
arra

array([1, 2, 3, 4])

In [5]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
ar = np.ones((3,5))
ar

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
a = np.empty((5,2))
a

array([[2.83763402e-316, 0.00000000e+000],
       [1.11475752e+261, 1.16318408e-028],
       [1.04914792e-153, 1.94918966e-153],
       [7.25382147e-043, 4.17700534e-057],
       [4.27780674e-033, 4.52385319e-091]])

In [16]:
an = np.arange(21)
an

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [19]:
an.reshape(7,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [22]:
linear_spaceeeee = np.linspace(1,6,3)
linear_spaceeeee

array([1. , 3.5, 6. ])

In [23]:
oneD_arr = np.arange(15)
oneD_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
twoD = oneD_arr.reshape(3,5)
twoD

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
threeD = np.arange(27).reshape(3,3,3)
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [27]:
new = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
new

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [28]:
new.shape

(2, 2, 3)

In [29]:
numarr = np.array([x for x in range(1,10)])
numarr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
numarr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
numa = np.array([x for x in range(1,13)])
numa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
numa.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
numa.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [35]:
numa.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [36]:
numa.reshape(3,2,3)

ValueError: ignored

In [37]:
numa.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
numa = numa.reshape(3,2,2)
numa

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [40]:
numa.reshape(-1)
#3D array has beeb flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
a = np.array([[1,2,3,],[4,5,6]])
b = np.array([4,5,6])
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([4, 5, 6]))

In [43]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
b

array([4, 5, 6])

In [45]:
np.add(a,b)

array([[ 5,  7,  9],
       [ 8, 10, 12]])

In [46]:
np.subtract(b,a)

array([[3, 3, 3],
       [0, 0, 0]])

In [47]:
np.multiply(a,b)

array([[ 4, 10, 18],
       [16, 25, 36]])

In [48]:
np.divide(a,b)

array([[0.25, 0.4 , 0.5 ],
       [1.  , 1.  , 1.  ]])

In [49]:
np.power(a,2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [50]:
np.power(a,b)

array([[    1,    32,   729],
       [  256,  3125, 46656]])